const fs = require("fs");
const path = require("path");

const iconsDir = path.join(__dirname, "../../Icons");
const output = path.join(iconsDir, "icons.js");

const baseURL =
  "https://raw.githubusercontent.com/nagisaya/surge/main/Icons/";

const files = fs
  .readdirSync(iconsDir)
  .filter(file => file.endsWith(".png"))
  .sort();

const icons = {};

for (const file of files) {
  const name = path.basename(file, ".png");
  icons[name] = `${baseURL}${file}`;
}

const content = `// Auto-generated by GitHub Actions\n\nexport default ${JSON.stringify(
  icons,
  null,
  2
)};\n`;

fs.writeFileSync(output, content);

console.log(`Generated ${files.length} icons`);
