[General]
#!include https://raw.githubusercontent.com/nagisaya/qvlmols/refs/heads/main/surge/Profile.conf

[Host]
#!include https://raw.githubusercontent.com/nagisaya/qvlmols/refs/heads/main/surge/Profile.conf

[Ponte]
#!include https://raw.githubusercontent.com/nagisaya/qvlmols/refs/heads/main/surge/Profile.conf

[Proxy]
#!include VPS.dconf

[Proxy Group]
#!include https://raw.githubusercontent.com/nagisaya/qvlmols/refs/heads/main/surge/Profile.conf
#!include PROXY GP.dconf

[Rule]
#!include https://raw.githubusercontent.com/nagisaya/qvlmols/refs/heads/main/surge/Profile.conf

[MITM]
#!include https://raw.githubusercontent.com/nagisaya/qvlmols/refs/heads/main/surge/Profile.conf