name: Qvl Iconset

permissions:
  contents: write

on:
  workflow_dispatch:

  push:
    paths:
      - "Icons/**/*.png"


concurrency:
  group: icon-generation
  cancel-in-progress: true


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22


      - name: Generate icons.json and icons.js
        run: |
          node Scripts/tools/generate-icons.js


      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Icons/icons.json Icons/icons.js

          git commit -m "Update icons database" || echo "No changes"

          git push